In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training")

print("Path to dataset files:", path)

C:\Users\majdz\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\majdz\.cache\kagglehub\datasets\ahmedmohamed2003\cafe-sales-dirty-data-for-cleaning-training\versions\1

In [2]:
import pandas as pd 
df = pd.read_csv(r'C:\internship_oasis_online\OIBSIP\DataAnalytics-L1-CleaningData\data\dirty_cafe_sales.csv')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [4]:
df.shape

(10000, 8)

In [5]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [9]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].unique()[:20])

--- Transaction ID ---
<StringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 'TXN_2548360', 'TXN_3051279', 'TXN_7619095', 'TXN_9437049', 'TXN_8915701',
 'TXN_2847255', 'TXN_3765707', 'TXN_6769710', 'TXN_8876618', 'TXN_3709394']
Length: 20, dtype: str

--- Item ---
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

--- Quantity ---
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

--- Price Per Unit ---
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

--- Total Spent ---
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

--- Payment Method ---
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

--- Location ---
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

--- Transaction Date ---
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 '2023-11-07',      'ERROR', '2023-05-03', '2023-06-01', '2023-03-21',
 '2023-11-15', '2023-06-10', '2023-02-24', '2023-03-25', '2023-01-15']
Length: 20, dtype: str

In [10]:
df['Item'].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [11]:
df['Quantity'].value_counts(dropna=False)

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

In [12]:
df['Price Per Unit'].value_counts(dropna=False)

Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64

In [13]:
df['Total Spent'].value_counts(dropna=False)

Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [14]:
df['Payment Method'].value_counts(dropna=False)

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [15]:
df['Location'].value_counts(dropna=False)

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [16]:
df['Transaction Date'].value_counts(dropna=False).head(20)

Transaction Date
NaN           159
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
2023-07-24     39
2023-09-21     39
2023-01-05     38
2023-06-18     37
2023-10-22     37
2023-01-25     37
2023-11-07     36
2023-04-30     36
2023-08-07     36
2023-01-12     36
2023-11-23     36
2023-06-30     36
2023-04-06     35
Name: count, dtype: int64

In [17]:
for col in ['Quantity', 'Price Per Unit', 'Total Spent']:
    numeric_values = pd.to_numeric(df[col], errors='coerce')
    print(f"\n--- {col} ---")
    print("Min:", numeric_values.min())
    print("Max:", numeric_values.max())

--- Quantity ---
Min: 1.0
Max: 5.0

--- Price Per Unit ---
Min: 1.0
Max: 5.0

--- Total Spent ---
Min: 1.0
Max: 25.0

In [18]:
df['Quantity'].value_counts()

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [19]:
quantity_numeric = pd.to_numeric(df['Quantity'], errors='coerce')

print("Median:", quantity_numeric.median())
print("\nValue counts:")
print(quantity_numeric.value_counts().sort_index())

Median: 3.0

Value counts:
Quantity
1.0    1822
2.0    1974
3.0    1849
4.0    1863
5.0    2013
Name: count, dtype: int64

In [20]:
quantity_numeric = pd.to_numeric(df['Quantity'], errors='coerce')

print("Missing or invalid Quantity values:", quantity_numeric.isna().sum())
print("\nValid Quantity values:")
print(quantity_numeric.value_counts().sort_index())

Missing or invalid Quantity values: 479

Valid Quantity values:
Quantity
1.0    1822
2.0    1974
3.0    1849
4.0    1863
5.0    2013
Name: count, dtype: int64

In [21]:
quantity_median = quantity_numeric.median()

print("Median Quantity:", quantity_median)

Median Quantity: 3.0

In [22]:
df['Quantity'] = quantity_numeric.fillna(quantity_median)

print("Missing Quantity after cleaning:", df['Quantity'].isna().sum())
print("\nQuantity values after cleaning:")
print(df['Quantity'].value_counts().sort_index())

Missing Quantity after cleaning: 0

Quantity values after cleaning:
Quantity
1.0    1822
2.0    1974
3.0    2328
4.0    1863
5.0    2013
Name: count, dtype: int64

### Cleaning Quantity

The `Quantity` column contained 479 invalid or missing values:
- 171 values recorded as `UNKNOWN`
- 170 values recorded as `ERROR`
- 138 missing values

The valid Quantity values ranged from 1 to 5. Since Quantity is a numerical variable and the invalid values could not be reliably recovered, they were replaced with the median of the valid values.

The median Quantity was **3.0**.

Using the median preserves all 10,000 transactions and avoids removing potentially useful records. After cleaning, there are no missing values in the `Quantity` column, and all values remain within the valid range of 1 to 5.

In [23]:
price_numeric = pd.to_numeric(df['Price Per Unit'], errors='coerce')

print("Missing or invalid Price Per Unit values:", price_numeric.isna().sum())
print("\nValid Price Per Unit values:")
print(price_numeric.value_counts().sort_index())

Missing or invalid Price Per Unit values: 533

Valid Price Per Unit values:
Price Per Unit
1.0    1143
1.5    1133
2.0    1227
3.0    2429
4.0    2331
5.0    1204
Name: count, dtype: int64

In [24]:
price_median = price_numeric.median()

print("Median Price Per Unit:", price_median)

Median Price Per Unit: 3.0

In [25]:
df['Price Per Unit'] = price_numeric.fillna(price_median)

print("Missing Price Per Unit after cleaning:", df['Price Per Unit'].isna().sum())

print("\nPrice Per Unit values after cleaning:")
print(df['Price Per Unit'].value_counts().sort_index())

Missing Price Per Unit after cleaning: 0

Price Per Unit values after cleaning:
Price Per Unit
1.0    1143
1.5    1133
2.0    1227
3.0    2962
4.0    2331
5.0    1204
Name: count, dtype: int64

In [26]:
total_spent_numeric = pd.to_numeric(df['Total Spent'], errors='coerce')

print("Missing or invalid Total Spent values:", total_spent_numeric.isna().sum())

print("\nValid Total Spent values:")
print(total_spent_numeric.value_counts().sort_index())

Missing or invalid Total Spent values: 502

Valid Total Spent values:
Total Spent
1.0     232
1.5     205
2.0     497
3.0     930
4.0     923
4.5     225
5.0     468
6.0     979
7.5     237
8.0     677
9.0     479
10.0    524
12.0    939
15.0    734
16.0    444
20.0    746
25.0    259
Name: count, dtype: int64

In [27]:
total_spent_median = total_spent_numeric.median()

print("Median Total Spent:", total_spent_median)

Median Total Spent: 8.0

In [28]:
df['Total Spent'] = total_spent_numeric.fillna(total_spent_median)

print("Missing Total Spent after cleaning:", df['Total Spent'].isna().sum())

print("\nTotal Spent values after cleaning:")
print(df['Total Spent'].value_counts().sort_index())

Missing Total Spent after cleaning: 0

Total Spent values after cleaning:
Total Spent
1.0      232
1.5      205
2.0      497
3.0      930
4.0      923
4.5      225
5.0      468
6.0      979
7.5      237
8.0     1179
9.0      479
10.0     524
12.0     939
15.0     734
16.0     444
20.0     746
25.0     259
Name: count, dtype: int64

### Cleaning Total Spent

The `Total Spent` column contained 502 invalid or missing values. The valid values ranged from 1.0 to 25.0.

Since `Total Spent` is a numerical monetary variable, the median was used to replace invalid and missing values. The median of the valid values was **8.0**.

The median was chosen because it is less sensitive to extreme values than the mean. After cleaning, all 10,000 records were retained and the `Total Spent` column contains no missing values.

In [29]:
print("Missing or invalid Item values:", df['Item'].isna().sum())

print("\nItem value counts:")
print(df['Item'].value_counts(dropna=False))

Missing or invalid Item values: 333

Item value counts:
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [30]:
item_mode = df.loc[~df['Item'].isin(['UNKNOWN', 'ERROR']), 'Item'].mode()[0]

print("Mode Item:", item_mode)

Mode Item: Juice

In [31]:
import numpy as np
df['Item'] = df['Item'].replace(['UNKNOWN', 'ERROR'], np.nan)
df['Item'] = df['Item'].fillna(item_mode)

print("Missing Item after cleaning:", df['Item'].isna().sum())

print("\nItem values after cleaning:")
print(df['Item'].value_counts())

Missing Item after cleaning: 0

Item values after cleaning:
Item
Juice       2140
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
Name: count, dtype: int64

### Cleaning Item

The `Item` column contained 969 unusable values:
- 344 `UNKNOWN`
- 292 `ERROR`
- 333 missing values

Since `Item` is a categorical variable, mode imputation was used. The mode among the valid item categories was **Juice**, so all invalid and missing values were replaced with `Juice`.

After cleaning, the `Item` column contains no missing or invalid values, and all 10,000 records are retained.

In [32]:
print("Missing or invalid Payment Method values:", df['Payment Method'].isna().sum())

print("\nPayment Method value counts:")
print(df['Payment Method'].value_counts(dropna=False))

Missing or invalid Payment Method values: 2579

Payment Method value counts:
Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [33]:
payment_mode = df.loc[
    ~df['Payment Method'].isin(['UNKNOWN', 'ERROR']),
    'Payment Method'
].mode()[0]

print("Mode Payment Method:", payment_mode)

Mode Payment Method: Digital Wallet

In [34]:
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN', 'ERROR'], np.nan)
df['Payment Method'] = df['Payment Method'].fillna(payment_mode)

print("Missing Payment Method after cleaning:", df['Payment Method'].isna().sum())

print("\nPayment Method values after cleaning:")
print(df['Payment Method'].value_counts())

Missing Payment Method after cleaning: 0

Payment Method values after cleaning:
Payment Method
Digital Wallet    5469
Credit Card       2273
Cash              2258
Name: count, dtype: int64

### Cleaning Payment Method

The `Payment Method` column contained 3,178 unusable values:
- 2,579 missing values
- 306 `ERROR`
- 293 `UNKNOWN`

Since `Payment Method` is a categorical variable, mode imputation was used. The most frequent valid category was **Digital Wallet**, so all invalid and missing values were replaced with `Digital Wallet.

After cleaning, the column contains no missing or invalid values. Because a substantial proportion of the original values were missing or invalid, the imputed values should be considered an approximation rather than the original payment methods.

In [35]:
print("Missing or invalid Location values:", df['Location'].isna().sum())

print("\nLocation value counts:")
print(df['Location'].value_counts(dropna=False))

Missing or invalid Location values: 3265

Location value counts:
Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [36]:
location_mode = df.loc[
    ~df['Location'].isin(['UNKNOWN', 'ERROR']),
    'Location'
].mode()[0]

print("Mode Location:", location_mode)

Mode Location: Takeaway

In [37]:
df['Location'] = df['Location'].replace(['UNKNOWN', 'ERROR'], np.nan)
df['Location'] = df['Location'].fillna(location_mode)

print("Missing Location after cleaning:", df['Location'].isna().sum())

print("\nLocation values after cleaning:")
print(df['Location'].value_counts())

Missing Location after cleaning: 0

Location values after cleaning:
Location
Takeaway    6983
In-store    3017
Name: count, dtype: int64

### Cleaning Location

The `Location` column contained 3,961 unusable values:
- 3,265 missing values
- 358 `ERROR`
- 338 `UNKNOWN`

Since `Location` is a categorical variable, mode imputation was used. The most frequent valid category was **Takeaway**, so all invalid and missing values were replaced with `Takeaway`.

After cleaning, the column contains no missing or invalid values. Because a substantial proportion of the original values were missing or invalid, the imputed values should be considered an approximation.

In [38]:
date_numeric = pd.to_datetime(
    df['Transaction Date'],
    errors='coerce',
    dayfirst=True
)

print("Missing or invalid Transaction Date values:", date_numeric.isna().sum())

print("\nSample of converted dates:")
print(date_numeric.head(10))

Missing or invalid Transaction Date values: 6258

Sample of converted dates:
0   2023-08-09
1          NaT
2          NaT
3          NaT
4   2023-11-06
5          NaT
6   2023-06-10
7          NaT
8          NaT
9          NaT
Name: Transaction Date, dtype: datetime64[us]

In [39]:
date_numeric = pd.to_datetime(
    df['Transaction Date'],
    errors='coerce',
    dayfirst=True
)

print("Missing or invalid Transaction Date values:", date_numeric.isna().sum())

print("\nSample of converted dates:")
print(date_numeric.head(10))

Missing or invalid Transaction Date values: 6258

Sample of converted dates:
0   2023-08-09
1          NaT
2          NaT
3          NaT
4   2023-11-06
5          NaT
6   2023-06-10
7          NaT
8          NaT
9          NaT
Name: Transaction Date, dtype: datetime64[us]

In [40]:
date_numeric = pd.to_datetime(
    df['Transaction Date'],
    errors='coerce',
    dayfirst=True
)

print("Missing or invalid Transaction Date values:", date_numeric.isna().sum())

print("\nSample of converted dates:")
print(date_numeric.head(10))

Missing or invalid Transaction Date values: 6258

Sample of converted dates:
0   2023-08-09
1          NaT
2          NaT
3          NaT
4   2023-11-06
5          NaT
6   2023-06-10
7          NaT
8          NaT
9          NaT
Name: Transaction Date, dtype: datetime64[us]

In [41]:
print(df['Transaction Date'].value_counts(dropna=False).head(30))

Transaction Date
NaN           159
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
2023-07-24     39
2023-09-21     39
2023-01-05     38
2023-06-18     37
2023-10-22     37
2023-01-25     37
2023-11-07     36
2023-04-30     36
2023-08-07     36
2023-01-12     36
2023-11-23     36
2023-06-30     36
2023-04-06     35
2023-10-08     35
2023-03-26     35
2023-09-06     35
2023-06-28     35
2023-04-20     34
2023-11-06     34
2023-12-09     34
2023-03-16     34
2023-05-18     34
2023-08-26     34
Name: count, dtype: int64

In [42]:
df['Transaction Date'] = pd.to_datetime(
    df['Transaction Date'],
    errors='coerce'
)

print("Missing/invalid dates after conversion:", df['Transaction Date'].isna().sum())
print(df['Transaction Date'].head(10))

Missing/invalid dates after conversion: 460
0   2023-09-08
1   2023-05-16
2   2023-07-19
3   2023-04-27
4   2023-06-11
5   2023-03-31
6   2023-10-06
7   2023-10-28
8   2023-07-28
9   2023-12-31
Name: Transaction Date, dtype: datetime64[us]

In [43]:
df = df.dropna(subset=['Transaction Date'])

print("Rows after removing invalid dates:", len(df))
print("Missing Transaction Date:", df['Transaction Date'].isna().sum())

Rows after removing invalid dates: 9540
Missing Transaction Date: 0

### Cleaning Transaction Date

The `Transaction Date` column contained 460 invalid or missing values:
- 159 `UNKNOWN`
- 142 `ERROR`
- 159 missing values

The valid date values were converted to the `datetime` data type using `pd.to_datetime()`.

Since a transaction date cannot be reliably inferred from the available data, the 460 records with invalid or missing dates were removed. This represents 4.6% of the original dataset, allowing the remaining records to retain reliable transaction dates for time-based analysis.

After cleaning, 9,540 records remain and there are no missing values in `Transaction Date`.

In [44]:
print("Item:")
print(df['Item'].unique())

print("\nPayment Method:")
print(df['Payment Method'].unique())

print("\nLocation:")
print(df['Location'].unique())

Item:
<StringArray>
['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Juice', 'Sandwich', 'Tea']
Length: 8, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'Digital Wallet']
Length: 3, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store']
Length: 2, dtype: str

In [45]:
print("Transaction Date dtype:", df['Transaction Date'].dtype)
print("Minimum date:", df['Transaction Date'].min())
print("Maximum date:", df['Transaction Date'].max())

Transaction Date dtype: datetime64[us]
Minimum date: 2023-01-01 00:00:00
Maximum date: 2023-12-31 00:00:00

In [46]:
Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df['Quantity'] < lower_bound) |
    (df['Quantity'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))

Q1: 2.0
Q3: 4.0
IQR: 2.0
Lower bound: -1.0
Upper bound: 7.0
Number of outliers: 0

### Outlier Detection — Quantity

The IQR method was used to detect outliers in the `Quantity` column.

- Q1 = 2.0
- Q3 = 4.0
- IQR = 2.0
- Lower bound = -1.0
- Upper bound = 7.0
- Number of outliers = 0

All values fall within the IQR bounds. Therefore, no outliers were detected and no values were removed or modified.

In [47]:
Q1 = df['Price Per Unit'].quantile(0.25)
Q3 = df['Price Per Unit'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df['Price Per Unit'] < lower_bound) |
    (df['Price Per Unit'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))

Q1: 2.0
Q3: 4.0
IQR: 2.0
Lower bound: -1.0
Upper bound: 7.0
Number of outliers: 0

### Outlier Detection — Price Per Unit

The IQR method was used to detect outliers in the `Price Per Unit` column.

- Q1 = 2.0
- Q3 = 4.0
- IQR = 2.0
- Lower bound = -1.0
- Upper bound = 7.0
- Number of outliers = 0

All values fall within the IQR bounds. Therefore, no outliers were detected and no values were removed or modified.

In [48]:
Q1 = df['Total Spent'].quantile(0.25)
Q3 = df['Total Spent'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df['Total Spent'] < lower_bound) |
    (df['Total Spent'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of outliers:", len(outliers))

Q1: 4.0
Q3: 12.0
IQR: 8.0
Lower bound: -8.0
Upper bound: 24.0
Number of outliers: 250

In [49]:
print(df.loc[df['Total Spent'] > 24, 'Total Spent'].value_counts())

Total Spent
25.0    250
Name: count, dtype: int64

### Outlier Detection — Total Spent

The IQR method identified 250 potential outliers in the `Total Spent` column.

- Q1 = 4.0
- Q3 = 12.0
- IQR = 8.0
- Lower bound = -8.0
- Upper bound = 24.0
- Number of detected outliers = 250

All 250 outliers have a value of **25.0**. Although these values are above the IQR upper bound, `25.0` is a valid value within the observed range of the dataset and does not indicate a data-entry error.

Therefore, the detected outliers were **retained** rather than removed or capped.

In [50]:
print(df.dtypes)

Transaction ID                 str
Item                           str
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [51]:
df['Quantity'] = df['Quantity'].astype('int64')

print(df['Quantity'].dtype)

int64

In [52]:
print(df.dtypes)

Transaction ID                 str
Item                           str
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [53]:
print("Rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())
print("\nMissing values:")
print(df.isna().sum())
print("\nData types:")
print(df.dtypes)

Rows: 9540
Duplicate rows: 0

Missing values:
Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

Data types:
Transaction ID                 str
Item                           str
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [54]:
before_after_summary = pd.DataFrame({
    'Metric': [
        'Row count',
        'Total missing values',
        'Duplicate rows',
        'Correct data types'
    ],
    'Before Cleaning': [
        10000,
        7226,
        0,
        '0 / 8'
    ],
    'After Cleaning': [
        len(df),
        df.isna().sum().sum(),
        df.duplicated().sum(),
        '8 / 8'
    ]
})

before_after_summary

                 Metric Before Cleaning After Cleaning
0             Row count           10000           9540
1  Total missing values            7226              0
2        Duplicate rows               0              0
3    Correct data types           0 / 8          8 / 8

In [55]:
df.to_csv('data/cleaned_cafe_sales.csv' , index = False)
print('cleaned csv saved successfully')

cleaned csv saved successfully

In [56]:
import os

print(os.path.exists('data/cleaned_cafe_sales.csv'))

True